name: InSession CI/CD
description: Build and deploy InSession Flutter app for iOS

trigger:
  branches:
    include:
      - ios-ui-improvements
      - master
      - copilot/troubleshoot-xcode-cloud-branch-issue
  
  pull_requests:
    branches:
      - master

steps:
  - name: Build iOS App
    platform: macos-sonoma
    xcode_version: 15.4
    
    environment_variables:
      - name: APP_STORE_CONNECT_USERNAME
        value: $(APP_STORE_CONNECT_USERNAME)
      - name: APP_STORE_CONNECT_PASSWORD
        value: $(APP_STORE_CONNECT_PASSWORD)
    
    post_actions:
      - name: Upload to TestFlight
        script: |
          # Note: The archive and export are handled automatically by Xcode Cloud
          # The IPA will be available in the default build output location
          # Upload to TestFlight if credentials are configured
          if [ -n "$APP_STORE_CONNECT_USERNAME" ] && [ -n "$APP_STORE_CONNECT_PASSWORD" ]; then
            xcrun altool --upload-app \
                         --type ios \
                         --file "build/ios/Runner.ipa" \
                         --username "$APP_STORE_CONNECT_USERNAME" \
                         --password "$APP_STORE_CONNECT_PASSWORD"
          else
            echo "TestFlight upload skipped - App Store Connect credentials not configured"
          fi

artifacts:
  - path: build/ios/ipa/*.ipa
    name: Runner iOS App
  - path: build/ios/archive/Runner.xcarchive
    name: iOS Archive

test_plans:
  - name: Unit Tests
    target: RunnerTests